rabbitmq_instances: 2
rabbitmq_image: rabbitmq:3-management
container_name: rabbitmq
network: rabbitmq_network
rabbitmq_port: 1567
rabbitmq_cookie: rabitmq_cluster_cookie
rabbitmq_user: batraman
rabbitmq_password: Passw0rd
docker_volume_default_path: /var/lib/docker/volumes
