---

- set_fact:
    docker_vol_path: []
    docker_vol_path_full: []

- set_fact:
    docker_vol_path: "{{ docker_vol_path }} + [ 'redis_data{{ item }}' ]"
  with_sequence: count="{{ redis_instances }}"
  no_log: true
  
- set_fact:
    docker_vol_path_full: "{{ docker_vol_path_full }} + [ '{{ item }}' ]"
  with_sequence: count="{{ redis_instances }}" format={{ docker_volume_default_path }}/redis_data%01x
  no_log: true
