redis_instances: 6
redis_port: 6379
redis_image: redis
container_name: redis
redis_network: redis_network
docker_volume_default_path: /var/lib/docker/volumes
set_cluster: true
cluster_config: |
  port {{ redis_port }}
  cluster-enabled yes
  cluster-config-file nodes.conf
  cluster-node-timeout 5000
  appendonly yes
